# CMake generated Testfile for 
# Source directory: C:/Users/bhask/Documents/PROJECTS/market-data-handler
# Build directory: C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[parser_nasdaq_itch]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_nasdaq_itch_parser.exe")
  set_tests_properties([=[parser_nasdaq_itch]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;376;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[parser_nasdaq_itch]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_nasdaq_itch_parser.exe")
  set_tests_properties([=[parser_nasdaq_itch]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;376;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[parser_nasdaq_itch]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_nasdaq_itch_parser.exe")
  set_tests_properties([=[parser_nasdaq_itch]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;376;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[parser_nasdaq_itch]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_nasdaq_itch_parser.exe")
  set_tests_properties([=[parser_nasdaq_itch]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;376;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[parser_nasdaq_itch]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[parser_nasdaq_itch_simd]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_nasdaq_itch_simd_parser.exe")
  set_tests_properties([=[parser_nasdaq_itch_simd]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;377;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[parser_nasdaq_itch_simd]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_nasdaq_itch_simd_parser.exe")
  set_tests_properties([=[parser_nasdaq_itch_simd]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;377;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[parser_nasdaq_itch_simd]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_nasdaq_itch_simd_parser.exe")
  set_tests_properties([=[parser_nasdaq_itch_simd]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;377;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[parser_nasdaq_itch_simd]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_nasdaq_itch_simd_parser.exe")
  set_tests_properties([=[parser_nasdaq_itch_simd]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;377;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[parser_nasdaq_itch_simd]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[parser_iex_deep]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_iex_deep_parser.exe")
  set_tests_properties([=[parser_iex_deep]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;378;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[parser_iex_deep]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_iex_deep_parser.exe")
  set_tests_properties([=[parser_iex_deep]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;378;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[parser_iex_deep]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_iex_deep_parser.exe")
  set_tests_properties([=[parser_iex_deep]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;378;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[parser_iex_deep]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_iex_deep_parser.exe")
  set_tests_properties([=[parser_iex_deep]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;378;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[parser_iex_deep]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[parser_cboe_pitch]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_cboe_pitch_parser.exe")
  set_tests_properties([=[parser_cboe_pitch]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;379;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[parser_cboe_pitch]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_cboe_pitch_parser.exe")
  set_tests_properties([=[parser_cboe_pitch]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;379;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[parser_cboe_pitch]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_cboe_pitch_parser.exe")
  set_tests_properties([=[parser_cboe_pitch]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;379;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[parser_cboe_pitch]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_cboe_pitch_parser.exe")
  set_tests_properties([=[parser_cboe_pitch]=] PROPERTIES  LABELS "parser" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;379;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[parser_cboe_pitch]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[core_spmc_seqlock_ring]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_core_spmc_seqlock_ring.exe")
  set_tests_properties([=[core_spmc_seqlock_ring]=] PROPERTIES  LABELS "core" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;381;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[core_spmc_seqlock_ring]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_core_spmc_seqlock_ring.exe")
  set_tests_properties([=[core_spmc_seqlock_ring]=] PROPERTIES  LABELS "core" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;381;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[core_spmc_seqlock_ring]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_core_spmc_seqlock_ring.exe")
  set_tests_properties([=[core_spmc_seqlock_ring]=] PROPERTIES  LABELS "core" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;381;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[core_spmc_seqlock_ring]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_core_spmc_seqlock_ring.exe")
  set_tests_properties([=[core_spmc_seqlock_ring]=] PROPERTIES  LABELS "core" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;381;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[core_spmc_seqlock_ring]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase2_sequence_tracker]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase2_sequence_tracker.exe")
  set_tests_properties([=[phase2_sequence_tracker]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;383;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase2_sequence_tracker]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase2_sequence_tracker.exe")
  set_tests_properties([=[phase2_sequence_tracker]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;383;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase2_sequence_tracker]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase2_sequence_tracker.exe")
  set_tests_properties([=[phase2_sequence_tracker]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;383;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase2_sequence_tracker]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase2_sequence_tracker.exe")
  set_tests_properties([=[phase2_sequence_tracker]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;383;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase2_sequence_tracker]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase2_recovery_merge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase2_recovery_merge.exe")
  set_tests_properties([=[phase2_recovery_merge]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;384;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase2_recovery_merge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase2_recovery_merge.exe")
  set_tests_properties([=[phase2_recovery_merge]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;384;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase2_recovery_merge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase2_recovery_merge.exe")
  set_tests_properties([=[phase2_recovery_merge]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;384;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase2_recovery_merge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase2_recovery_merge.exe")
  set_tests_properties([=[phase2_recovery_merge]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;384;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase2_recovery_merge]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase2_recovery_simulator]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase2_recovery_simulator.exe")
  set_tests_properties([=[phase2_recovery_simulator]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;385;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase2_recovery_simulator]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase2_recovery_simulator.exe")
  set_tests_properties([=[phase2_recovery_simulator]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;385;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase2_recovery_simulator]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase2_recovery_simulator.exe")
  set_tests_properties([=[phase2_recovery_simulator]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;385;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase2_recovery_simulator]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase2_recovery_simulator.exe")
  set_tests_properties([=[phase2_recovery_simulator]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;385;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase2_recovery_simulator]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase2_recovery_pending_dedupe]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase2_recovery_pending_dedupe.exe")
  set_tests_properties([=[phase2_recovery_pending_dedupe]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;386;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase2_recovery_pending_dedupe]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase2_recovery_pending_dedupe.exe")
  set_tests_properties([=[phase2_recovery_pending_dedupe]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;386;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase2_recovery_pending_dedupe]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase2_recovery_pending_dedupe.exe")
  set_tests_properties([=[phase2_recovery_pending_dedupe]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;386;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase2_recovery_pending_dedupe]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase2_recovery_pending_dedupe.exe")
  set_tests_properties([=[phase2_recovery_pending_dedupe]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;386;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase2_recovery_pending_dedupe]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase2_determinism_crc]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase2_determinism_crc.exe")
  set_tests_properties([=[phase2_determinism_crc]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;387;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase2_determinism_crc]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase2_determinism_crc.exe")
  set_tests_properties([=[phase2_determinism_crc]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;387;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase2_determinism_crc]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase2_determinism_crc.exe")
  set_tests_properties([=[phase2_determinism_crc]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;387;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase2_determinism_crc]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase2_determinism_crc.exe")
  set_tests_properties([=[phase2_determinism_crc]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;387;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase2_determinism_crc]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase2_pipeline]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase2_pipeline.exe")
  set_tests_properties([=[phase2_pipeline]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;388;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase2_pipeline]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase2_pipeline.exe")
  set_tests_properties([=[phase2_pipeline]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;388;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase2_pipeline]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase2_pipeline.exe")
  set_tests_properties([=[phase2_pipeline]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;388;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase2_pipeline]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase2_pipeline.exe")
  set_tests_properties([=[phase2_pipeline]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;388;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase2_pipeline]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase2_jit_bridge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase2_jit_bridge.exe")
  set_tests_properties([=[phase2_jit_bridge]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;389;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase2_jit_bridge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase2_jit_bridge.exe")
  set_tests_properties([=[phase2_jit_bridge]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;389;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase2_jit_bridge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase2_jit_bridge.exe")
  set_tests_properties([=[phase2_jit_bridge]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;389;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase2_jit_bridge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase2_jit_bridge.exe")
  set_tests_properties([=[phase2_jit_bridge]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;389;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase2_jit_bridge]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase2_ab_arbiter]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase2_ab_arbiter.exe")
  set_tests_properties([=[phase2_ab_arbiter]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;390;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase2_ab_arbiter]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase2_ab_arbiter.exe")
  set_tests_properties([=[phase2_ab_arbiter]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;390;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase2_ab_arbiter]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase2_ab_arbiter.exe")
  set_tests_properties([=[phase2_ab_arbiter]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;390;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase2_ab_arbiter]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase2_ab_arbiter.exe")
  set_tests_properties([=[phase2_ab_arbiter]=] PROPERTIES  LABELS "phase2" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;390;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase2_ab_arbiter]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase3_feature_bridge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase3_feature_bridge.exe")
  set_tests_properties([=[phase3_feature_bridge]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;392;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase3_feature_bridge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase3_feature_bridge.exe")
  set_tests_properties([=[phase3_feature_bridge]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;392;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase3_feature_bridge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase3_feature_bridge.exe")
  set_tests_properties([=[phase3_feature_bridge]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;392;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase3_feature_bridge]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase3_feature_bridge.exe")
  set_tests_properties([=[phase3_feature_bridge]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;392;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase3_feature_bridge]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase3_feature_pipeline]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase3_feature_pipeline.exe")
  set_tests_properties([=[phase3_feature_pipeline]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;393;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase3_feature_pipeline]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase3_feature_pipeline.exe")
  set_tests_properties([=[phase3_feature_pipeline]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;393;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase3_feature_pipeline]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase3_feature_pipeline.exe")
  set_tests_properties([=[phase3_feature_pipeline]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;393;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase3_feature_pipeline]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase3_feature_pipeline.exe")
  set_tests_properties([=[phase3_feature_pipeline]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;393;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase3_feature_pipeline]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase3_order_book_nbbo]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase3_order_book_nbbo.exe")
  set_tests_properties([=[phase3_order_book_nbbo]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;394;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase3_order_book_nbbo]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase3_order_book_nbbo.exe")
  set_tests_properties([=[phase3_order_book_nbbo]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;394;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase3_order_book_nbbo]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase3_order_book_nbbo.exe")
  set_tests_properties([=[phase3_order_book_nbbo]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;394;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase3_order_book_nbbo]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase3_order_book_nbbo.exe")
  set_tests_properties([=[phase3_order_book_nbbo]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;394;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase3_order_book_nbbo]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase3_book_snapshot]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase3_book_snapshot.exe")
  set_tests_properties([=[phase3_book_snapshot]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;395;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase3_book_snapshot]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase3_book_snapshot.exe")
  set_tests_properties([=[phase3_book_snapshot]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;395;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase3_book_snapshot]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase3_book_snapshot.exe")
  set_tests_properties([=[phase3_book_snapshot]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;395;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase3_book_snapshot]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase3_book_snapshot.exe")
  set_tests_properties([=[phase3_book_snapshot]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;395;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase3_book_snapshot]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase3_book_reconciliation]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase3_book_reconciliation.exe")
  set_tests_properties([=[phase3_book_reconciliation]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;396;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase3_book_reconciliation]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase3_book_reconciliation.exe")
  set_tests_properties([=[phase3_book_reconciliation]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;396;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase3_book_reconciliation]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase3_book_reconciliation.exe")
  set_tests_properties([=[phase3_book_reconciliation]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;396;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase3_book_reconciliation]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase3_book_reconciliation.exe")
  set_tests_properties([=[phase3_book_reconciliation]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;396;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase3_book_reconciliation]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase3_intrusive_order_book]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase3_intrusive_order_book.exe")
  set_tests_properties([=[phase3_intrusive_order_book]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;397;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase3_intrusive_order_book]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase3_intrusive_order_book.exe")
  set_tests_properties([=[phase3_intrusive_order_book]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;397;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase3_intrusive_order_book]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase3_intrusive_order_book.exe")
  set_tests_properties([=[phase3_intrusive_order_book]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;397;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase3_intrusive_order_book]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase3_intrusive_order_book.exe")
  set_tests_properties([=[phase3_intrusive_order_book]=] PROPERTIES  LABELS "phase3" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;397;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase3_intrusive_order_book]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase4_sim_matching_engine]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase4_sim_matching_engine.exe")
  set_tests_properties([=[phase4_sim_matching_engine]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;399;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase4_sim_matching_engine]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase4_sim_matching_engine.exe")
  set_tests_properties([=[phase4_sim_matching_engine]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;399;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase4_sim_matching_engine]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase4_sim_matching_engine.exe")
  set_tests_properties([=[phase4_sim_matching_engine]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;399;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase4_sim_matching_engine]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase4_sim_matching_engine.exe")
  set_tests_properties([=[phase4_sim_matching_engine]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;399;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase4_sim_matching_engine]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase4_market_making_strategy]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase4_market_making_strategy.exe")
  set_tests_properties([=[phase4_market_making_strategy]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;400;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase4_market_making_strategy]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase4_market_making_strategy.exe")
  set_tests_properties([=[phase4_market_making_strategy]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;400;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase4_market_making_strategy]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase4_market_making_strategy.exe")
  set_tests_properties([=[phase4_market_making_strategy]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;400;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase4_market_making_strategy]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase4_market_making_strategy.exe")
  set_tests_properties([=[phase4_market_making_strategy]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;400;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase4_market_making_strategy]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase4_pnl_accountant]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase4_pnl_accountant.exe")
  set_tests_properties([=[phase4_pnl_accountant]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;401;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase4_pnl_accountant]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase4_pnl_accountant.exe")
  set_tests_properties([=[phase4_pnl_accountant]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;401;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase4_pnl_accountant]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase4_pnl_accountant.exe")
  set_tests_properties([=[phase4_pnl_accountant]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;401;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase4_pnl_accountant]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase4_pnl_accountant.exe")
  set_tests_properties([=[phase4_pnl_accountant]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;401;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase4_pnl_accountant]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase4_backtest_runner]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase4_backtest_runner.exe")
  set_tests_properties([=[phase4_backtest_runner]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;402;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase4_backtest_runner]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase4_backtest_runner.exe")
  set_tests_properties([=[phase4_backtest_runner]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;402;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase4_backtest_runner]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase4_backtest_runner.exe")
  set_tests_properties([=[phase4_backtest_runner]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;402;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase4_backtest_runner]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase4_backtest_runner.exe")
  set_tests_properties([=[phase4_backtest_runner]=] PROPERTIES  LABELS "phase4" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;402;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase4_backtest_runner]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase_e_histogram]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase_e_histogram.exe")
  set_tests_properties([=[phase_e_histogram]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;420;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase_e_histogram]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase_e_histogram.exe")
  set_tests_properties([=[phase_e_histogram]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;420;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase_e_histogram]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase_e_histogram.exe")
  set_tests_properties([=[phase_e_histogram]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;420;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase_e_histogram]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase_e_histogram.exe")
  set_tests_properties([=[phase_e_histogram]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;420;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase_e_histogram]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase_e_run_metadata]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase_e_run_metadata.exe")
  set_tests_properties([=[phase_e_run_metadata]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;421;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase_e_run_metadata]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase_e_run_metadata.exe")
  set_tests_properties([=[phase_e_run_metadata]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;421;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase_e_run_metadata]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase_e_run_metadata.exe")
  set_tests_properties([=[phase_e_run_metadata]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;421;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase_e_run_metadata]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase_e_run_metadata.exe")
  set_tests_properties([=[phase_e_run_metadata]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;421;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase_e_run_metadata]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[phase_e_sweep_smoke]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_phase_e_sweep_smoke.exe")
  set_tests_properties([=[phase_e_sweep_smoke]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;422;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[phase_e_sweep_smoke]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_phase_e_sweep_smoke.exe")
  set_tests_properties([=[phase_e_sweep_smoke]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;422;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[phase_e_sweep_smoke]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_phase_e_sweep_smoke.exe")
  set_tests_properties([=[phase_e_sweep_smoke]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;422;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[phase_e_sweep_smoke]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_phase_e_sweep_smoke.exe")
  set_tests_properties([=[phase_e_sweep_smoke]=] PROPERTIES  LABELS "phase_e" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;422;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[phase_e_sweep_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[research_simulation_clock]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_research_simulation_clock.exe")
  set_tests_properties([=[research_simulation_clock]=] PROPERTIES  LABELS "research" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;425;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[research_simulation_clock]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_research_simulation_clock.exe")
  set_tests_properties([=[research_simulation_clock]=] PROPERTIES  LABELS "research" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;425;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[research_simulation_clock]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_research_simulation_clock.exe")
  set_tests_properties([=[research_simulation_clock]=] PROPERTIES  LABELS "research" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;425;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[research_simulation_clock]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_research_simulation_clock.exe")
  set_tests_properties([=[research_simulation_clock]=] PROPERTIES  LABELS "research" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;425;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[research_simulation_clock]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[research_strategy_engine]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_research_strategy_engine.exe")
  set_tests_properties([=[research_strategy_engine]=] PROPERTIES  LABELS "research" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;426;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[research_strategy_engine]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_research_strategy_engine.exe")
  set_tests_properties([=[research_strategy_engine]=] PROPERTIES  LABELS "research" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;426;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[research_strategy_engine]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_research_strategy_engine.exe")
  set_tests_properties([=[research_strategy_engine]=] PROPERTIES  LABELS "research" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;426;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[research_strategy_engine]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_research_strategy_engine.exe")
  set_tests_properties([=[research_strategy_engine]=] PROPERTIES  LABELS "research" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;426;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[research_strategy_engine]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[runtime_shard_router]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_runtime_shard_router.exe")
  set_tests_properties([=[runtime_shard_router]=] PROPERTIES  LABELS "runtime" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;428;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[runtime_shard_router]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_runtime_shard_router.exe")
  set_tests_properties([=[runtime_shard_router]=] PROPERTIES  LABELS "runtime" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;428;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[runtime_shard_router]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_runtime_shard_router.exe")
  set_tests_properties([=[runtime_shard_router]=] PROPERTIES  LABELS "runtime" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;428;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[runtime_shard_router]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_runtime_shard_router.exe")
  set_tests_properties([=[runtime_shard_router]=] PROPERTIES  LABELS "runtime" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;428;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[runtime_shard_router]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[runtime_sharded_pipeline_determinism]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Debug/test_runtime_sharded_pipeline_determinism.exe")
  set_tests_properties([=[runtime_sharded_pipeline_determinism]=] PROPERTIES  LABELS "runtime" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;429;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[runtime_sharded_pipeline_determinism]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/Release/test_runtime_sharded_pipeline_determinism.exe")
  set_tests_properties([=[runtime_sharded_pipeline_determinism]=] PROPERTIES  LABELS "runtime" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;429;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[runtime_sharded_pipeline_determinism]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/MinSizeRel/test_runtime_sharded_pipeline_determinism.exe")
  set_tests_properties([=[runtime_sharded_pipeline_determinism]=] PROPERTIES  LABELS "runtime" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;429;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[runtime_sharded_pipeline_determinism]=] "C:/Users/bhask/Documents/PROJECTS/market-data-handler/build_phase_e_win/RelWithDebInfo/test_runtime_sharded_pipeline_determinism.exe")
  set_tests_properties([=[runtime_sharded_pipeline_determinism]=] PROPERTIES  LABELS "runtime" _BACKTRACE_TRIPLES "C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;371;add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;429;mf_add_test;C:/Users/bhask/Documents/PROJECTS/market-data-handler/CMakeLists.txt;0;")
else()
  add_test([=[runtime_sharded_pipeline_determinism]=] NOT_AVAILABLE)
endif()
