#include "mf/research/alpha_lab/tearsheet.hpp"

#include <cstdio>
#include <fstream>
#include <iomanip>

namespace mf::research::alpha_lab {

bool TearsheetWriter::write_markdown(const std::string& path, const TearsheetInput& in) const {
  std::ofstream out(path);
  if (!out) {
    return false;
  }
  out << "# Alpha Research Lab Tearsheet\n\n";
  out << "**Status:** Generated by `tools/alpha_lab`\n\n";
  out << "**CAVEAT:** Offline replay with simulated fills proxy. No latency or adverse-selection model.\n\n";
  out << "## Data\n";
  out << "- Journal: `" << in.journal << "`\n";
  out << "- Feature rows: " << in.materialize.feature_rows << "\n";
  out << "- Journal CRC: `";
  char crc_hex[16];
  std::snprintf(crc_hex, sizeof(crc_hex), "0x%08x", in.materialize.journal_crc);
  out << crc_hex << "`\n";
  out << "- Materialize wall time: " << std::fixed << std::setprecision(2) << in.materialize.wall_seconds
      << "s\n";
  out << "- Trials logged: " << in.n_trials << "\n";
  out << "- CV folds: " << in.folds.size() << "\n\n";

  out << "## Top signals (OOS mean IC)\n";
  out << "| signal | horizon_ns | mean_ic | std_ic | mean_quintile_spread |\n|---|---:|---:|---:|---:|\n";
  for (std::size_t i = 0; i < in.signals.size() && i < 10; ++i) {
    const auto& s = in.signals[i];
    out << "| " << s.signal << " | " << s.horizon_ns << " | " << s.mean_ic << " | " << s.std_ic << " | "
        << s.mean_quintile_spread << " |\n";
  }
  out << "\n";

  out << "## Failed / weak signals\n";
  if (in.failed_signals.empty()) {
    out << "- (none flagged)\n\n";
  } else {
    for (const auto& s : in.failed_signals) {
      out << "- `" << s.signal << "` @ " << s.horizon_ns << "ns: mean_ic=" << s.mean_ic << "\n";
    }
    out << "\n";
  }

  out << "## Multiple-testing correction\n";
  for (std::size_t i = 0; i < in.dsr_results.size(); ++i) {
    out << "- DSR #" << i << ": deflated_sharpe=" << in.dsr_results[i].deflated_sharpe
        << ", p=" << in.dsr_results[i].p_value << "\n";
  }
  for (std::size_t i = 0; i < in.pbo_results.size(); ++i) {
    out << "- PBO #" << i << ": probability=" << in.pbo_results[i].probability << "\n";
  }
  out << "\n";

  out << "## Capacity\n";
  out << "- Capacity ceiling (net Sharpe > 0): participation=" << in.capacity_ceiling << "\n";
  out << "- See `capacity_curve.csv`\n\n";

  out << "## Ablation\n";
  out << "| variant | mean_ic | quintile_spread | net_sharpe |\n|---|---:|---:|---:|\n";
  for (const auto& row : in.ablation) {
    out << "| " << row.variant << " | " << row.mean_ic << " | " << row.mean_quintile_spread << " | "
        << row.net_sharpe << " |\n";
  }
  out << "\n";

  out << "## Phase 0 baseline comparison\n";
  out << "- OFI holdout Sharpe: " << in.baseline_sharpe << " (`baseline_ofi_backtest.md`)\n";
  return true;
}

bool TearsheetWriter::write_json(const std::string& path, const TearsheetInput& in) const {
  std::ofstream out(path);
  if (!out) {
    return false;
  }
  out << "{\n";
  out << "  \"journal\": \"" << in.journal << "\",\n";
  out << "  \"feature_rows\": " << in.materialize.feature_rows << ",\n";
  out << "  \"journal_crc\": " << in.materialize.journal_crc << ",\n";
  out << "  \"n_trials\": " << in.n_trials << ",\n";
  out << "  \"n_signals_evaluated\": " << in.signals.size() << ",\n";
  out << "  \"capacity_ceiling\": " << in.capacity_ceiling << ",\n";
  out << "  \"baseline_sharpe\": " << in.baseline_sharpe << ",\n";
  out << "  \"top_signal\": ";
  if (in.signals.empty()) {
    out << "null,\n";
  } else {
    out << "{\"name\":\"" << in.signals.front().signal << "\",\"horizon_ns\":"
        << in.signals.front().horizon_ns << ",\"mean_ic\":" << in.signals.front().mean_ic << "},\n";
  }
  if (!in.dsr_results.empty()) {
    out << "  \"dsr_p_value\": " << in.dsr_results.front().p_value << ",\n";
  }
  if (!in.pbo_results.empty()) {
    out << "  \"pbo_probability\": " << in.pbo_results.front().probability << ",\n";
  }
  out << "  \"failed_signal_count\": " << in.failed_signals.size() << "\n";
  out << "}\n";
  return true;
}

bool TearsheetWriter::write_signal_survival_csv(const std::string& path, const TearsheetInput& in) const {
  std::ofstream out(path);
  if (!out) {
    return false;
  }
  out << "signal,horizon_ns,mean_ic,std_ic,mean_quintile_spread,survived_dsr\n";
  for (std::size_t i = 0; i < in.signals.size(); ++i) {
    const auto& s = in.signals[i];
    const bool survived = i < in.dsr_results.size() ? in.dsr_results[i].p_value < 0.05 : false;
    out << s.signal << ',' << s.horizon_ns << ',' << s.mean_ic << ',' << s.std_ic << ','
        << s.mean_quintile_spread << ',' << (survived ? "true" : "false") << '\n';
  }
  return true;
}

bool TearsheetWriter::write_capacity_csv(
    const std::string& path,
    const std::vector<CapacityPoint>& curve) const {
  std::ofstream out(path);
  if (!out) {
    return false;
  }
  out << "participation,gross_sharpe,net_sharpe,mean_return\n";
  for (const auto& pt : curve) {
    out << pt.participation << ',' << pt.gross_sharpe << ',' << pt.net_sharpe << ',' << pt.mean_return
        << '\n';
  }
  return true;
}

bool TearsheetWriter::write_folds_json(const std::string& path, const std::vector<CvFold>& folds) const {
  std::ofstream out(path);
  if (!out) {
    return false;
  }
  out << "[\n";
  for (std::size_t i = 0; i < folds.size(); ++i) {
    const auto& f = folds[i];
    out << "  {\"fold_id\":" << f.fold_id << ",\"test_start_ns\":" << f.test_start_ns
        << ",\"test_end_ns\":" << f.test_end_ns << ",\"train_count\":" << f.train_indices.size()
        << ",\"test_count\":" << f.test_indices.size() << "}";
    if (i + 1 < folds.size()) {
      out << ',';
    }
    out << '\n';
  }
  out << "]\n";
  return true;
}

bool TearsheetWriter::write_ablation_md(
    const std::string& path,
    const std::vector<AblationRow>& rows) const {
  std::ofstream out(path);
  if (!out) {
    return false;
  }
  out << "# Alpha Lab Ablation\n\n";
  out << "| variant | mean_ic | quintile_spread | net_sharpe |\n|---|---:|---:|---:|\n";
  for (const auto& row : rows) {
    out << "| " << row.variant << " | " << row.mean_ic << " | " << row.mean_quintile_spread << " | "
        << row.net_sharpe << " |\n";
  }
  return true;
}

}  // namespace mf::research::alpha_lab
